import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex w-full mt-[200px] h-full justify-center items-center">
          Landing Page Of Selexome
      </div>
    </>
  )
}