import Head from 'next/head'
import Row from '../components/Row';
import CircularProgress from '@mui/material/CircularProgress'
import { getProducts } from '../api';

interface IHomeProps {
  products: {
    id: number;
    discount: number;
    price: number;
    title: string;
    imageUrl: string;
  }[];
}

export default function Home({ products }: IHomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {products ? (
        <div className="w-full h-full flex justify-center items-center">
          <Row products={products} />
        </div>
      ) : (
        <div className="w-full h-full flex justify-center items-center">
          <CircularProgress />
        </div>
      )}

    </>
  )
}


export async function getStaticProps() {
  let data = null;
  await getProducts().then((res) => { data = JSON.parse(JSON.stringify(res.data)) })

  return {
    props: data,
  }
}